Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/shashwat/.espressif/python_env/idf5.3_py3.10_env/lib/python3.10/site-packages/esptool/__main__.py", line 9, in <module>
    esptool._main()
  File "/home/shashwat/.espressif/python_env/idf5.3_py3.10_env/lib/python3.10/site-packages/esptool/__init__.py", line 1139, in _main
    main()
  File "/home/shashwat/.espressif/python_env/idf5.3_py3.10_env/lib/python3.10/site-packages/esptool/__init__.py", line 712, in main
    esp = esp or get_default_connected_device(
  File "/home/shashwat/.espressif/python_env/idf5.3_py3.10_env/lib/python3.10/site-packages/esptool/__init__.py", line 1024, in get_default_connected_device
    _esp.connect(before, connect_attempts)
  File "/home/shashwat/.espressif/python_env/idf5.3_py3.10_env/lib/python3.10/site-packages/esptool/loader.py", line 678, in connect
    last_error = self._connect_attempt(reset_strategy, mode)
  File "/home/shashwat/.espressif/python_env/idf5.3_py3.10_env/lib/python3.10/site-packages/esptool/loader.py", line 578, in _connect_attempt
    self.flush_input()
  File "/home/shashwat/.espressif/python_env/idf5.3_py3.10_env/lib/python3.10/site-packages/esptool/loader.py", line 492, in flush_input
    self._port.flushInput()
  File "/home/shashwat/.espressif/python_env/idf5.3_py3.10_env/lib/python3.10/site-packages/serial/serialutil.py", line 588, in flushInput
    self.reset_input_buffer()
  File "/home/shashwat/.espressif/python_env/idf5.3_py3.10_env/lib/python3.10/site-packages/serial/serialposix.py", line 683, in reset_input_buffer
    self._reset_input_buffer()
  File "/home/shashwat/.espressif/python_env/idf5.3_py3.10_env/lib/python3.10/site-packages/serial/serialposix.py", line 677, in _reset_input_buffer
    termios.tcflush(self.fd, termios.TCIFLUSH)
termios.error: (5, 'Input/output error')
CMake Error at run_serial_tool.cmake:66 (message):
  
  /home/shashwat/.espressif/python_env/idf5.3_py3.10_env/bin/python;;/home/shashwat/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32
  failed.



